DROP DATABASE IF EXISTS CoursesDB;
CREATE DATABASE CoursesDB;
USE CoursesDB;
CREATE TABLE STUDENT (
	Name VARCHAR(64),
	StudentSSN VARCHAR(64)
);

CREATE TABLE FACULTY (
	Name VARCHAR(64),
	FacSSN VARCHAR(64)
);

CREATE TABLE COURSES (
	CourseName VARCHAR(64),
	Number INT
);
